#!/bin/bash
# =========================================================
# 帝国理工 HPC 任务配置
# =========================================================
#PBS -lselect=1:ncpus=1:mem=16gb
#PBS -lwalltime=72:00:00
#PBS -J 1-15
#PBS -N Micro_Final

# 更改下方路径为你自己的帝国理工用户名，用于保存日志
#PBS -o /rds/general/user/zw2425/home/Paper9/log/
#PBS -e /rds/general/user/zw2425/home/Paper9/log/

# 自动切换到你运行 qsub 命令时所在的目录
cd $PBS_O_WORKDIR

# ==========================================
# 核心：初始化并激活你的个人 Conda 环境
# ==========================================
# 初始化 conda 命令行工具
source /rds/general/user/zw2425/home/miniforge3/etc/profile.d/conda.sh

# 激活你配置好的 R 环境
conda activate r441

# 运行你的 R 脚本
echo "Running chunk ${PBS_ARRAY_INDEX} at $(date)"

Rscript MicroBioclim_Final.R ${PBS_ARRAY_INDEX}

echo "Chunk ${PBS_ARRAY_INDEX} finished at $(date)"
