#!/bin/bash
#PBS -lselect=1:ncpus=1:mem=16gb
#PBS -lwalltime=72:00:00
#PBS -J 1-15
#PBS -N Micro_Final

# Specify the log path
#PBS -o /rds/general/user/zw2425/home/Paper9/log/
#PBS -e /rds/general/user/zw2425/home/Paper9/log/

# Switch to the working dir
cd $PBS_O_WORKDIR

# Source my conda env
source /rds/general/user/zw2425/home/miniforge3/etc/profile.d/conda.sh

# Activate the R env preset before
conda activate r441

# Rscript
echo "Running chunk ${PBS_ARRAY_INDEX} at $(date)"

Rscript MicroBioclim_Final.R ${PBS_ARRAY_INDEX}

echo "Chunk ${PBS_ARRAY_INDEX} finished at $(date)"
